project:
  type: book
  output-dir: docs

book:
  title: "University of Chicago Political Science Math Prefresher"
  author: "Anton Strezhnev"
  date: "9/12/2022"
  chapters:
    - index.qmd
    - 02_sets_and_functions.qmd
    - 03_limits.qmd
    - 04_calculus.qmd
    - 05_optimization.qmd
    - 06_probability.qmd
    - 07_linear-algebra.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



